FROM postgres:10.21

ARG CODA_AUTH_SERVICE_DB_USERNAME=${CODA_AUTH_SERVICE_DB_USERNAME}
ARG CODA_AUTH_SERVICE_DB_PASSWORD=${CODA_AUTH_SERVICE_DB_PASSWORD}
ARG CODA_AUTH_SERVICE_DB_NAME=${CODA_AUTH_SERVICE_DB_NAME}

ENV POSTGRES_USER=${CODA_AUTH_SERVICE_DB_USERNAME}
ENV POSTGRES_PASSWORD=${CODA_AUTH_SERVICE_DB_PASSWORD}
ENV POSTGRES_DB=${CODA_AUTH_SERVICE_DB_NAME}