ARG AUTH_SERVICE_DB_USERNAME=${AUTH_SERVICE_DB_USERNAME}
ARG AUTH_SERVICE_DB_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
ARG AUTH_SERVICE_DB_NAME=${AUTH_SERVICE_DB_NAME}

ENV POSTGRES_USER=${AUTH_SERVICE_DB_USERNAME}
ENV POSTGRES_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
ENV POSTGRES_DB=${AUTH_SERVICE_DB_NAME}

FROM postgres:10.21